### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by kennywk** [johnmerm/javartc#1]
Just wondering if this works or just an experiment? I'm looking into a similar use case where i need my java server to handle webrtc connections from the browser using libjitsi. The only difference is that i want to create a gateway/bridge type of environment (not using xmpp).

**Comment by johnmerm** [comment]
It's highly experimental, half complete and dormant at the moment. To my disdappointment, libjitsi does not implement the same variants of webRTC as browsers do. E.g. It does not (at least  Feb 2016) support bundled streams, and the VP8 implementation throws some errors when called.

**Comment by kennywk** [comment]
Thanks,

I've looked at the Jitsi Meet / Video Bridge. I like the capability, but i
don't want to have to run it over a xmpp infrastructure as i already have
extensive non-xmpp messaging already.... Something light weight that is
full java and cross platform is the key... Kurento seems awesome but
requires Ubuntu...

Thanks for the response.... i guess i'll keep looking.

K

**Comment by johnmerm** [comment]
If you don't need to communicate with firefox/chorme but can use standalone java (swt) clients, I suppose libjitsi will be fine for you. Look at the AVReceive2 and AVtransmit2 [examples ](https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/examples/) for more.

Thanks for waking the project up.
